sudo: required
language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install ansible
  - pip install flake8
  - ansible --version

# command to run tests
script:
  # - flake8 . --show-source --max-line-length=120 --statistics --count -qq
  - ansible-playbook playbook_aix_suma_targets_all.yml --syntax-check
  - ansible-playbook playbook_aix_suma_targets_all.yml -vvv
  - ansible-playbook playbook_aix_suma_targets_list.yml --syntax-check
  - ansible-playbook playbook_aix_suma_targets_list.yml -vvv
  - ansible-playbook playbook_aix_suma_targets_range.yml --syntax-check
  - ansible-playbook playbook_aix_suma_targets_range.yml -vvv
  - ansible-playbook playbook_aix_suma_targets_star.yml --syntax-check
  - ansible-playbook playbook_aix_suma_targets_star.yml -vvv




