---
- name: "SUMA on AIX"
  hosts: all
  gather_facts: yes

  tasks:

  #######################################################################
  ### AIX SUMA: All targets
  #######################################################################

  - name: "AIX SUMA: All targets"
    aix_suma:
      oslevel: '7100-04-02-1614'
      location: ''
      targets: all
      action: download
    ignore_errors: True

    register: targets
  - debug: var=targets.debug_targets
